packages:
  - 'packages/demos/CentralPark'
  - 'packages/demos/GoldenGatePark'
  - 'packages/demos/Hamarikyu'
  - 'packages/demos/Hasedera'
  - 'packages/demos/Horyuji'
  - 'packages/demos/ImperialPalace'
  - 'packages/demos/Kenchoji'
  - 'packages/demos/KodomoNoKuni'
  - 'packages/demos/KoishikawaBotanicalGarden'
  - 'packages/demos/MeijiJingu'
  - 'packages/demos/Saidaiji'
  - 'packages/demos/Sankeien'
  - 'packages/demos/Sensoji'
  - 'packages/demos/ShinjukuGyoenNationalPark'
  - 'packages/demos/ShowaKinenPark'
  - 'packages/demos/TaimaDera'
  - 'packages/demos/TokyoDisneyLand'
  - 'packages/demos/UnivOfTokyo-Hongo'
  - 'packages/demos/UnivOfTokyo-Komaba'
  - 'packages/demos/Yugyoji'
  - 'packages/demos/Zoorasia'
  - 'packages/tools'
