packages:
  - 'packages/demos/CentralPark'
  - 'packages/demos/GoldenGatePark'
  - 'packages/demos/KodomoNoKuni'
  - 'packages/demos/Sankeien'
  - 'packages/demos/ShinjukuGyoenNationalPark'
  - 'packages/demos/Yugyoji'
  - 'packages/tools'
