packages:
  - 'packages/demos/CentralPark'
  - 'packages/demos/EnoshimaJinja'
  - 'packages/demos/FushimiInari'
  - 'packages/demos/GoldenGatePark'
  - 'packages/demos/Hamarikyu'
  - 'packages/demos/Hasedera'
  - 'packages/demos/Hieizan'
  - 'packages/demos/Hieizan-Yokawa'
  - 'packages/demos/HokkaidoUniv'
  - 'packages/demos/Horyuji'
  - 'packages/demos/ImperialPalace'
  - 'packages/demos/KasugaTaisha'
  - 'packages/demos/Kenchoji'
  - 'packages/demos/KiiFudokiNoOka'
  - 'packages/demos/KodomoNoKuni'
  - 'packages/demos/KoishikawaBotanicalGarden'
  - 'packages/demos/KyotoUniv'
  - 'packages/demos/KyushuUniv'
  - 'packages/demos/MeijiJingu'
  - 'packages/demos/NagoyaUniv'
  - 'packages/demos/OmiwaJinja'
  - 'packages/demos/OsakaUniv'
  - 'packages/demos/Saidaiji'
  - 'packages/demos/Sankeien'
  - 'packages/demos/Sensoji'
  - 'packages/demos/ShinjukuGyoenNationalPark'
  - 'packages/demos/ShowaKinenPark'
  - 'packages/demos/TaimaDera'
  - 'packages/demos/TohokuUniv'
  - 'packages/demos/TokyoDisneyLand'
  - 'packages/demos/TokyoNationalMuseum'
  - 'packages/demos/Tomogashima'
  - 'packages/demos/UnivOfTokyo-Hongo'
  - 'packages/demos/UnivOfTokyo-Komaba'
  - 'packages/demos/WakayamaCastle'
  - 'packages/demos/Yugyoji'
  - 'packages/demos/Zoorasia'
  - 'packages/tools'
