packages:
  - 'packages/demos/CentralPark'
  - 'packages/demos/GoldenGatePark'
  - 'packages/demos/Hamarikyu'
  - 'packages/demos/Hasedera'
  - 'packages/demos/Horyuji'
  - 'packages/demos/Kenchoji'
  - 'packages/demos/KodomoNoKuni'
  - 'packages/demos/KoishikawaBotanicalGarden'
  - 'packages/demos/MeijiJingu'
  - 'packages/demos/Saidaiji'
  - 'packages/demos/Sankeien'
  - 'packages/demos/ShinjukuGyoenNationalPark'
  - 'packages/demos/TokyoDisneyLand'
  - 'packages/demos/Yugyoji'
  - 'packages/demos/Zoorasia'
  - 'packages/tools'
