packages:
  - packages/demos/CentralPark
  - packages/demos/Engakuji
  - packages/demos/EnoshimaJinja
  - packages/demos/Expo2025
  - packages/demos/FushimiInari
  - packages/demos/GoldenGatePark
  - packages/demos/Gumyoji
  - packages/demos/Hamarikyu
  - packages/demos/Hasedera
  - packages/demos/HeijoKyuseki
  - packages/demos/Hieizan
  - packages/demos/Hieizan-Yokawa
  - packages/demos/HokkaidoUniv
  - packages/demos/Horyuji
  - packages/demos/ImperialPalace
  - packages/demos/KanazawaZoo
  - packages/demos/KasugaTaisha
  - packages/demos/KawasakiDaishi
  - packages/demos/Kenchoji
  - packages/demos/KiiFudokiNoOka
  - packages/demos/KodomoNoKuni
  - packages/demos/Kofukuji
  - packages/demos/KoishikawaBotanicalGarden
  - packages/demos/Kotokuin
  - packages/demos/KumamotoCastle
  - packages/demos/KyotoUniv
  - packages/demos/KyushuUniv
  - packages/demos/MeijiJingu
  - packages/demos/NagoyaCastle
  - packages/demos/NagoyaUniv
  - packages/demos/NogeyamaZoo
  - packages/demos/NonHoiPark
  - packages/demos/OmiwaJinja
  - packages/demos/OsakaCastle
  - packages/demos/OsakaUniv
  - packages/demos/Saidaiji
  - packages/demos/Sankeien
  - packages/demos/Sensoji
  - packages/demos/ShinjukuGyoenNationalPark
  - packages/demos/ShowaKinenPark
  - packages/demos/TaimaDera
  - packages/demos/Todaiji
  - packages/demos/TohokuUniv
  - packages/demos/TokyoDisneyLand
  - packages/demos/TokyoNationalMuseum
  - packages/demos/Tomogashima
  - packages/demos/Toshodaiji
  - packages/demos/TsurugaokaHachimanGu
  - packages/demos/TsurumiPark
  - packages/demos/UenoPark
  - packages/demos/UnivOfTokyo-Hongo
  - packages/demos/UnivOfTokyo-Komaba
  - packages/demos/WakayamaCastle
  - packages/demos/Yakushiji
  - packages/demos/YamashitaPark
  - packages/demos/YokohamaMunicipalChildrensBotanicalGarden
  - packages/demos/YoyogiPark
  - packages/demos/Yugyoji
  - packages/demos/Zoorasia
  - packages/tools
overrides:
  '@daijimaps/svgmapviewer': link:../../../../.local/share/pnpm/global/5/node_modules/@daijimaps/svgmapviewer
